name: Update Changelog

on: 
  push:
    branches:
      - main

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.3
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup Node and restore cached dependencies
        uses: actions/setup-node@v4

      - name: Build 
        run: bun run build
