name: Update Changelog

on: 
  push:
    branches:
      - main

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x

      - name: Setup Node and restore cached dependencies
        uses: actions/setup-node@v4
        with:
          cache: 'bun'

      - name: Install packages
        run: bun install --frozen-lockfile
      - name: Build 
        run: bun run build
